```{r}
library(tidyverse)
library(glue)
library(sf)
library(dplyr)
```

```{r}
census <- read_csv("./data/census.csv")
burglaries <- read_csv("./data/burglaries_2023.csv")

dc_shape_file <- st_read("./data/DC")
```
```{r}
dc_crs <- st_crs(dc_shape_file)
```

```{r}
#glimpse(burglaries)
```

```{r}
burglaries_geo <- st_as_sf(burglaries |> drop_na(latitude, longitude),
         coords = c('longitude', 'latitude'),
         crs = "NAD83")
```

```{r}

burglaries_geo |> 
  ggplot() +
  geom_sf()


dc_shape_file |> 
  ggplot() +
  geom_sf() +
  geom_sf()

```


```{r}
?st_join()
burglaries_dc <- st_join(dc_shape_file, burglaries_geo, join = st_contains)

burglaries_dc |>
  distinct(TRACTCE) |>
  nrow()
```

```{r}
dc_shape_file |>
  ggplot() +
  geom_sf() +
  geom_sf(data = burglaries_dc,  size = 0.1)
```
```{r}
merged_df <- full_join(census, burglaries_dc, by = c("tract" = "TRACTCE")) |> view()
```
```{r}
merged_df |>
  group_by(tract) |>
  distinct(incident_number) |>
  nrow()
```

```{r}

burgles_per_tract <- merged_df |>
  group_by(tract) |>
  distinct(incident_number) |>
  summarize(num_burgles = n()) |>
  arrange(desc(num_burgles))

burgles_per_tract 
```

```{r}
str(merged_df)
```


```{r}
burgles_per_tract_per_cap <- merged_df |>
  filter(population != 0) |>
  group_by(tract) |>
  distinct(incident_number, .keep_all = TRUE) |>
  summarise(
    population = first(population),
    median_income = first(median_income),
    num_burgles = n(),
    bpc = (n() / population) * 1000) |>
  arrange(desc(bpc))

burgles_per_tract_per_cap
```
```{r}
burgles_lm <- lm(" median_income ~ bpc", data = burgles_per_tract_per_cap)
```

```{r}
summary(burgles_lm)
```

```{r}
pr_burgles_const <- glm('num_burgles ~ 1',
               data = burgles_per_tract_per_cap,
               family = poisson)
summary(pr_burgles_const)
```

```{r}
mu = exp(coef(pr_burgles_const))
```

```{r}
x <- 0:5
y <- dpois(x, lambda = mu)

tibble(x = x, y = y) |> 
  ggplot(aes(x = x, y = y)) + 
  geom_col()
```
```{r}
pr_burgles <- glm('num_burgles ~ median_income',
               data = filtered_burgles,
               family = poisson)
```

```{r}
summary(pr_burgles)
```
```{r}
filtered_burgles <- burgles_per_tract_per_cap |>
  filter(median_income > 0)

summary(filtered_burgles$median_income)

```

```{r}
est_df <- tibble(
  median_income = seq(from = min(filtered_burgles$median_income, na.rm = TRUE), 
                          to = max(filtered_burgles$median_income, na.rm = TRUE), 
                          length.out = 100)
    )

est_df <- est_df |> 
  bind_cols(predict(pr_burgles, newdata = est_df, type = "response")) |> 
  rename("Estimated Mean Number of Burgles" = "...2")
            
est_df |> 
  ggplot(aes(x = median_income, y = `Estimated Mean Number of Burgles`)) +
  geom_line() +
  scale_x_continuous(labels = scales::comma)
```
```{r}
pr_burgles <- glm('num_burgles ~ median_income',
               data = filtered_burgles,
               family = poisson,
               offset = log(population))
summary(pr_burgles)
```

```{r}
est_df <- tibble(
  median_income = seq(from = min(filtered_burgles$median_income, na.rm = TRUE), 
                          to = max(filtered_burgles$median_income, na.rm = TRUE), 
                          length.out = 100),
  population = 1000
    )

est_df <- est_df |> 
  bind_cols(predict(pr_burgles, newdata = est_df, type = "response")) |> 
  rename("Burglaries per tract per 1000 people" = "...3")

filtered_burgles |> 
  ggplot(aes(x = median_income, y = `bpc`)) +
  geom_point() +
  geom_line(data = est_df, aes(x = median_income, y = `Burglaries per tract per 1000 people`))
```
```{r}
burgles_by_place <- burglaries_dc |>
  st_drop_geometry() |>
  group_by(location_description) |>
  distinct(incident_number, .keep_all = TRUE) |>
  summarise(
    num_burgles = n()
  )
  
burgles_by_place |>
  ggplot(aes(x = location_description, y = num_burgles)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
burgles_by_place <- burglaries_dc |>
  st_drop_geometry() |>
  group_by(location_description) |>
  distinct(incident_number, .keep_all = TRUE) |>
  summarise(
    num_burgles = n()
  )
  
burgles_by_place |>
  ggplot(aes(x = location_description, y = num_burgles)) +
  geom_col() +
  scale_y_continuous(trans = 'log', labels = scales::comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
burgles_by_place |>
  ggplot(aes(x = "", y = num_burgles, fill = location_description)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") + 
  theme_void()
```





